import = [
    "~/.config/alacritty/themes/themes/alacritty_0_12.toml"
]

[env]
TERM = "tmux-256color"

[window]
opacity = 0.9


[font]
size = 12.0

normal = { family = "SauceCodePro Nerd Font", style = "Regular"}
bold = { family = "SauceCodePro Nerd Font", style = "Bold"}
italic = { family = "SauceCodePro Nerd Font", style = "Italic"}
bold_italic = { family = "SauceCodePro Nerd Font", style = "Bold Italic"}
